Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        'aliyun_3_x64_20G_alibase_20240528.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-beijing
          - cn-shanghai
          - ap-southeast-1
          - cn-qingdao
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-2
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - eu-west-1
          - me-east-1
          - eu-central-1
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序（不支持示例应用）
            Description: 上传zip源代码包或者从Git仓库拉取更新，滚动更新ECS实例上的应用程序。示例应用不支持更新。
            Type: Custom
            Parameters:
              - FileUrl
              - Branch
              - CommitHash
              - AppUpdateBatchSize
              - AppUpdatePauseTime
          - Name: 修改ECS实例配置
            Description: 修改ECS实例配置，可能会重启ECS实例
            Type: Custom
            Parameters:
              # 注释掉的不支持更新
              - HostPort
              - EcsInstanceType
              - InternetMaxBandwidthOut
              - SystemDiskCategory
              - SystemDiskSize
              # - KeyPairName
              # - BackendProtocol
              # - ListenerProtocol
              - MaxInstanceCount
              - MinInstanceCount
          - Name: 修改数据库实例配置
            Description: 修改数据库实例配置，可能会重启数据库实例
            Type: Custom
            Parameters:
              - ProvisionDatabase
              - DBCategory
              - DBInstanceClass
              - DBInstanceStorage
              - DBInstanceStorageType
              # does not support update
              # - Engine
              # - EngineVersion
              - SslCertificate
          - Name: 修改数据库账号或密码
            Type: Custom
            Parameters:
              - DBUser
              - DBPassword
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Name: Docker Web应用
    ShortDescription: 基于Alibaba Cloud Linux3部署用户自定义的Docker Web应用。支持用户上传源代码zip包或者从指定Git仓库拉取源代码部署、更新应用。支持单实例或高可用两种部署模式。
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: aliyun_3_2104_docker_26
    Description: Docker 26 on Alibaba cloud linux 3.2104
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
    SupportRegionIds:
      - cn-hangzhou
      - cn-beijing
      - cn-shanghai
      - ap-southeast-1
      - cn-qingdao
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-nanjing
      - cn-shenzhen
      - cn-heyuan
      - cn-guangzhou
      - cn-fuzhou
      - cn-wuhan-lr
      - cn-chengdu
      - cn-hongkong
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-2
      - ap-southeast-3
      - ap-southeast-6
      - ap-southeast-5
      - ap-southeast-7
      - us-east-1
      - us-west-1
      - eu-west-1
      - me-east-1
      - eu-central-1
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    # 使用最新的LTS版本Alibaba Cloud Linux
    SourceImageId: aliyun_3_x64_20G_alibase_20240819.vhd
    SystemDiskSize: 20
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunShellScript
    Timeout: 10800
    CommandContent: |-
      #!/bin/bash
      yum check-update
      yum -y upgrade --security
      yum -y upgrade-minimal

      # 安装docker-ce
      yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
      yum makecache
      yum install -y wget curl unzip git
      yum install -y docker-ce
      systemctl enable docker
      mkdir -p /etc/docker
      tee /etc/docker/daemon.json <<-'EOF'
      {
          "registry-mirrors": [
              "https://mirrors-ssl.aliyuncs.com/"
          ]
      }
      EOF
      systemctl restart docker
      
      # 关闭基础镜像非必要服务，降低基础服务资源占用
      systemctl stop systemd-resolved.service
      systemctl disable systemd-resolved.service
      systemctl stop rpcbind.socket
      systemctl stop rpcbind.service
      systemctl disable rpcbind.service
      systemctl disable rpcbind.socket


      function clean_log(){
          rm -fv /usr/local/aegis/aegis_update/data/data.[0-9]
          rm -fv /usr/local/aegis/aegis_client/aegis_*/data/data.[0-9]

          rm -fv /usr/local/aegis/globalcfg/domaincfg.ini 
          rm -fv /opt/aegis/globalcfg/domaincfg.ini
          if [[ -e /usr/local/aegis/globalcfg/domaincfg.ini ]] || [[ -e /opt/aegis/globalcfg/domaincfg.ini ]];then
              return 1
          fi

          rm -f /var/log/anaconda.*
          rm -f /var/log/sa/*
          rm -rf /var/log/conman*
          [ -f /var/log/messages ] && >  /var/log/messages
          rm -f /var/log/*.[0-9]*
          rm -f dmesg*
          rm -rfv /var/lib/apt/lists/*
          rm -rfv /var/log/installer/syslog
          rm -rfv /var/log/journal/*
          rm -rfv /var/log/installer/cdebconf/questions.dat
          rm -rfv /var/cache/yum/*
          rm -rfv /var/cache/dnf/*
          rm -rfv /var/lib/yum/history/*
          rm -rfv /var/lib/dnf/history*
          rm -rfv /var/lib/dhclient/*
          rm -rfv /var/lib/dhcp/*
          rm -rfv /var/lib/aliyun_init/*
          rm -rfv /var/lib/cloud
          rm -rfv /etc/ssh/sshd_config.d/50-cloud-init.conf

          if [ -d /usr/local/share/aliyun-assist/*/log/ ];then
              rm -rfv  /usr/local/share/aliyun-assist/*/log/*
          fi
          rm -rf /usr/local/share/aliyun-assist/plugin
          rm -rf  /var/log/ecsgo.log*

          rm -rf /tmp/*
          rm -f /root/{.bash_history,.viminfo,*.cfg,*.log*}
          rm -rf /root/script

          for i in $(find /var/log/ -type f); do > $i; done

          sed -i "/iZ*Z/d" /etc/hosts
          sed -i "/AliYun/d" /etc/hosts
          # for ubuntu22/24 use cloud-init autoinstall remained hostnaem Aliyun
          sed -i "/Aliyun/d" /etc/hosts
          sed -i "/debug/d" /etc/hosts
          # Clean up useless nameservers to prevent cloudinit local domain name resolution timeout
          sed -i "/nameserver/d" $(realpath /etc/resolv.conf)
          rm -rfv /tmp/*
          [ -d /etc/NetworkManager/system-connections ] && rm -fv /etc/NetworkManager/system-connections/*.nmconnection
          if [[ ! -L /etc/udev/rules.d/70-persistent-net.rules ]];then
              rm -rfv /etc/udev/rules.d/70-persistent-net.rules
          fi
          sync
          sync
          sync
      }

      function clean_source_cache(){
          if [ `which zypper` ]; then
              zypper clean; rm -fv /etc/zypp/repos.d/CUSTOM*
          elif [ `which apt-get` ]; then
              apt-get -q clean; apt-get -q autoclean; apt-get -q -y autoremove;
          elif [ `which yum` ]; then
              yum clean all;
          elif [ `which pkg` ]; then
              pkg autoremove
          fi
      }

      function clean_root_passwd(){
          passwd -l root
          sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config
          echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config
          sed -i -e 's/root:[^:]*:/root:*:/g' /etc/shadow

          rm -f /root/.ssh/known_hosts
          rm -f /etc/ssh/ssh_host_*
      }


      function clean_cmd_history(){
        for user in $(cut -f1 -d: /etc/passwd); do
            if [ -f /home/$user/.bash_history ]; then
                > /home/$user/.bash_history
            fi
        done
        > /root/.bash_history
      }

      clean_source_cache
      clean_log
      clean_root_passwd
      clean_cmd_history