Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        'aliyun_3_x64_20G_alibase_20240528.vhd':
          # 复用docker ce社区版服务的部署物
          ArtifactId: artifact-6312bbc1751943678574
          ArtifactVersion: 2
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-beijing
          - cn-shanghai
          - ap-southeast-1
          - cn-qingdao
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-2
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - eu-west-1
          - me-east-1
          - eu-central-1
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序（不支持示例应用）
            Description: 上传zip源代码包或者从Git仓库拉取更新，滚动更新ECS实例上的应用程序。示例应用不支持更新。
            Type: Custom
            Parameters:
              - FileUrl
              - Branch
              - CommitHash
              - AppUpdateBatchSize
              - AppUpdatePauseTime
          - Name: 修改ECS实例配置
            Description: 修改ECS实例配置，可能会重启ECS实例
            Type: Custom
            Parameters:
              # 注释掉的不支持更新
              - HostPort
              - EcsInstanceType
              - InternetMaxBandwidthOut
              - SystemDiskCategory
              - SystemDiskSize
              # - KeyPairName
              # - BackendProtocol
              # - ListenerProtocol
              - MaxInstanceCount
              - MinInstanceCount
          - Name: 修改数据库实例配置
            Description: 修改数据库实例配置，可能会重启数据库实例
            Type: Custom
            Parameters:
              - ProvisionDatabase
              - DBCategory
              - DBInstanceClass
              - DBInstanceStorage
              - DBInstanceStorageType
              # does not support update
              # - Engine
              # - EngineVersion
              - SslCertificate
          - Name: 修改数据库账号或密码
            Type: Custom
            Parameters:
              - DBUser
              - DBPassword
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Name: Docker Web应用
    ShortDescription: 基于Alibaba Cloud Linux3部署用户自定义的Docker Web应用。支持用户上传源代码zip包或者从指定Git仓库拉取源代码部署、更新应用。支持单实例或高可用两种部署模式。
    Image: 'resources/icons/service_logo.png'